# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeerLove' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeerLove

  target 'BeerLoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeerLoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
