# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BeerLove' do

pod 'MVCarouselCollectionView', '~> 1.0.5'

pod 'Fabric'

pod 'Crashlytics'

end

