# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WeHeartBeer' do

pod 'Parse'

end

target 'WeHeartBeerTests' do

end

target 'WeHeartBeerUITests' do

end

